import SwiftUI

struct PuzzleModel: Hashable, Codable {
    let image: String
    let name: String
    let ingredients: String
    let cookingTime: String
    let recipe: String
    let xPosition: [CGFloat]
    let yPosition: [CGFloat]
    let puzzleImages: [String]
}

struct BitesDifficultyModel {
    //MARK: - EASY
    let easyPuzzle = [PuzzleModel(image: BitesImageName.easy1.rawValue,
                                  name: "Chocolate Fondue",
                                  ingredients: "200 g dark chocolate, 150 ml cream (20-30%), fruits and berries of your choice.",
                                  cookingTime: "10 minutes",
                                  recipe: "Melt the chocolate with cream in a water bath until smooth. Prepare sliced fruits or berries. Serve warm, dipping pieces into the chocolate.",
                                  xPosition: [5.8, 2.61, 1.62, 1.241, 5.12, 2.46, 1.684, 1.278, 5.8, 2.775, 1.753, 1.279, 5.8, 2.6, 1.62, 1.242],
                                  yPosition: [1.5, 1.5, 1.5, 1.471, 1.83, 1.83, 1.787, 1.746, 2.275, 2.275, 2.275, 2.21, 3, 3, 3.13, 3.01],
                                  puzzleImages: [BitesImageName.easyPart1.rawValue,
                                                 BitesImageName.easyPart2.rawValue,
                                                 BitesImageName.easyPart3.rawValue,
                                                 BitesImageName.easyPart4.rawValue,
                                                 BitesImageName.easyPart5.rawValue,
                                                 BitesImageName.easyPart6.rawValue,
                                                 BitesImageName.easyPart7.rawValue,
                                                 BitesImageName.easyPart8.rawValue,
                                                 BitesImageName.easyPart9.rawValue,
                                                 BitesImageName.easyPart10.rawValue,
                                                 BitesImageName.easyPart11.rawValue,
                                                 BitesImageName.easyPart12.rawValue,
                                                 BitesImageName.easyPart13.rawValue,
                                                 BitesImageName.easyPart14.rawValue,
                                                 BitesImageName.easyPart15.rawValue,
                                                 BitesImageName.easyPart16.rawValue]),
                      PuzzleModel(image: BitesImageName.easy2.rawValue,
                                  name: "Cotton Cake (Japanese Cheesecake)",
                                  ingredients: "200 g cream cheese, 50 g butter, 120 ml milk, 60 g flour, 20 g cornstarch, 6 eggs, 140 g sugar.",
                                  cookingTime: "1 hour 30 minutes",
                                  recipe: "Mix melted cheese, butter, and milk; add flour and yolks, then gently fold in whipped egg whites with sugar. Bake in a water bath at 160°C (320°F) for 60 minutes, cool, and serve.",
                                  xPosition: [4.9, 2.55, 1.72, 1.26, 5.55, 2.551, 1.593, 1.2239, 4.92, 2.41, 1.653, 1.26, 4.9, 2.545, 1.72, 1.26],
                                  yPosition: [1.495, 1.466, 1.466, 1.466, 1.78, 1.78, 1.74, 1.78, 2.2, 2.265, 2.2, 2.335, 2.99, 2.99, 2.99, 3.11],
                                  puzzleImages: [BitesImageName.easy2part1.rawValue,
                                                 BitesImageName.easy2part2.rawValue,
                                                 BitesImageName.easy2part3.rawValue,
                                                 BitesImageName.easy2part4.rawValue,
                                                 BitesImageName.easy2part5.rawValue,
                                                 BitesImageName.easy2part6.rawValue,
                                                 BitesImageName.easy2part7.rawValue,
                                                 BitesImageName.easy2part8.rawValue,
                                                 BitesImageName.easy2part9.rawValue,
                                                 BitesImageName.easy2part10.rawValue,
                                                 BitesImageName.easy2part11.rawValue,
                                                 BitesImageName.easy2part12.rawValue,
                                                 BitesImageName.easy2part13.rawValue,
                                                 BitesImageName.easy2part14.rawValue,
                                                 BitesImageName.easy2part15.rawValue,
                                                 BitesImageName.easy2part16.rawValue]),
                      PuzzleModel(image: BitesImageName.easy3.rawValue,
                                  name: "Croquembouche",
                                  ingredients: "20 profiteroles, 200 g sugar, 50 ml water, whipped cream or custard.",
                                  cookingTime: "2 hours",
                                  recipe: "Fill profiteroles with cream. Boil sugar with water to make caramel, dip profiteroles, and stack them into a pyramid. Let the caramel harden before serving.",
                                  xPosition: [5.6, 2.57, 1.66, 1.27, 4.95, 2.42, 1.599, 1.235, 5.6, 2.56, 1.662, 1.27, 4.95, 2.56, 1.73, 1.273],
                                  yPosition: [1.495, 1.495, 1.495, 1.466, 1.82, 1.82, 1.82, 1.778, 2.331, 2.331, 2.26, 2.33, 3.11, 3.11, 2.985, 3.104],
                                  puzzleImages: [BitesImageName.easy3part1.rawValue,
                                                 BitesImageName.easy3part2.rawValue,
                                                 BitesImageName.easy3part3.rawValue,
                                                 BitesImageName.easy3part4.rawValue,
                                                 BitesImageName.easy3part5.rawValue,
                                                 BitesImageName.easy3part6.rawValue,
                                                 BitesImageName.easy3part7.rawValue,
                                                 BitesImageName.easy3part8.rawValue,
                                                 BitesImageName.easy3part9.rawValue,
                                                 BitesImageName.easy3part10.rawValue,
                                                 BitesImageName.easy3part11.rawValue,
                                                 BitesImageName.easy3part12.rawValue,
                                                 BitesImageName.easy3part13.rawValue,
                                                 BitesImageName.easy3part14.rawValue,
                                                 BitesImageName.easy3part15.rawValue,
                                                 BitesImageName.easy3part16.rawValue]),
                      PuzzleModel(image: BitesImageName.easy4.rawValue,
                                  name: "Eclairs",
                                  ingredients: "125 ml water, 50 g butter, 75 g flour, 2 eggs, 200 g custard, 100 g chocolate.",
                                  cookingTime: "1 hour 15 minutes",
                                  recipe: "Prepare choux pastry, bake eclairs for 25 minutes at 200°C (390°F). Let them cool, fill with custard, and glaze with melted chocolate.",
                                  xPosition: [4.95, 2.418, 1.6, 1.23, 4.95, 2.42, 1.66, 1.266, 4.95, 2.42, 1.663, 1.266, 4.95, 2.56, 1.66, 1.23],
                                  yPosition: [1.495, 1.466, 1.465, 1.465, 1.78, 1.74, 1.74, 1.739, 2.2, 2.2, 2.265, 2.2, 2.99, 2.99, 3.11, 2.99],
                                  puzzleImages: [BitesImageName.easy4part1.rawValue,
                                                 BitesImageName.easy4part2.rawValue,
                                                 BitesImageName.easy4part3.rawValue,
                                                 BitesImageName.easy4part4.rawValue,
                                                 BitesImageName.easy4part5.rawValue,
                                                 BitesImageName.easy4part6.rawValue,
                                                 BitesImageName.easy4part7.rawValue,
                                                 BitesImageName.easy4part8.rawValue,
                                                 BitesImageName.easy4part9.rawValue,
                                                 BitesImageName.easy4part10.rawValue,
                                                 BitesImageName.easy4part11.rawValue,
                                                 BitesImageName.easy4part12.rawValue,
                                                 BitesImageName.easy4part13.rawValue,
                                                 BitesImageName.easy4part14.rawValue,
                                                 BitesImageName.easy4part15.rawValue,
                                                 BitesImageName.easy4part16.rawValue])]
    //MARK: - MEDIUM
    let mediumPuzzle = [PuzzleModel(image: BitesImageName.medium1.rawValue,
                                    name: "Klafuti (Clafoutis)",
                                    ingredients: "300 g cherries, 100 g flour, 100 g sugar, 3 eggs, 200 ml milk, 50 g butter.",
                                    cookingTime: "40 minutes",
                                    recipe: "300 g cherries, 100 g flour, 100 g sugar, 3 eggs, 200 ml milk, 50 g butter.",
                                    xPosition: [5.6, 3.04, 2.01, 1.46, 1.198, 6.25, 3.04, 2.01, 1.545, 1.226, 6.25, 3.25, 2.02, 1.465, 1.201, 6.25, 3.05, 2.019, 1.506, 1.201, 6.25, 3.05, 1.945, 1.465, 1.201],
                                    yPosition: [1.445, 1.445, 1.445, 1.445, 1.445, 1.645, 1.675, 1.645, 1.675, 1.645, 1.95, 2.032, 1.95, 2.035, 1.95, 2.4, 2.46, 2.397, 2.46, 2.398, 3.11, 3.11, 3.11, 3.11, 3.11],
                                    puzzleImages: [BitesImageName.medium1part1.rawValue,
                                                   BitesImageName.medium1part2.rawValue,
                                                   BitesImageName.medium1part3.rawValue,
                                                   BitesImageName.medium1part4.rawValue,
                                                   BitesImageName.medium1part5.rawValue,
                                                   BitesImageName.medium1part6.rawValue,
                                                   BitesImageName.medium1part7.rawValue,
                                                   BitesImageName.medium1part8.rawValue,
                                                   BitesImageName.medium1part9.rawValue,
                                                   BitesImageName.medium1part10.rawValue,
                                                   BitesImageName.medium1part11.rawValue,
                                                   BitesImageName.medium1part12.rawValue,
                                                   BitesImageName.medium1part13.rawValue,
                                                   BitesImageName.medium1part14.rawValue,
                                                   BitesImageName.medium1part15.rawValue,
                                                   BitesImageName.medium1part16.rawValue,
                                                   BitesImageName.medium1part17.rawValue,
                                                   BitesImageName.medium1part18.rawValue,
                                                   BitesImageName.medium1part19.rawValue,
                                                   BitesImageName.medium1part20.rawValue,
                                                   BitesImageName.medium1part21.rawValue,
                                                   BitesImageName.medium1part22.rawValue,
                                                   BitesImageName.medium1part23.rawValue,
                                                   BitesImageName.medium1part24.rawValue,
                                                   BitesImageName.medium1part25.rawValue]),
                        PuzzleModel(image: BitesImageName.medium2.rawValue,
                                    name: "Macarons",
                                    ingredients: "100 g almond flour, 100 g powdered sugar, 100 g sugar, 2 egg whites, filling of your choice.",
                                    cookingTime: "2 hours",
                                    recipe: "Whip egg whites with sugar, mix in almond flour and powdered sugar, pipe rounds, and bake at 150°C (300°F) for 15 minutes. Sandwich two shells with filling.",
                                    xPosition: [6, 2.98, 1.98, 1.526, 1.214, 5.4, 2.98, 2.06, 1.528, 1.215, 5.4, 2.98, 1.99, 1.489, 1.216, 5.4, 2.825, 1.92, 1.49, 1.216, 5.4, 2.98, 1.99, 1.45, 1.19],
                                    yPosition: [1.468, 1.445, 1.445, 1.445, 1.445, 1.677, 1.647, 1.645, 1.675, 1.675, 1.99, 1.95, 1.95, 2.035, 2.035, 2.52, 2.455, 2.397, 2.52, 2.455, 3.21, 3.21, 3.103, 3.21, 3.105],
                                    puzzleImages: [BitesImageName.medium2part1.rawValue,
                                                   BitesImageName.medium2part2.rawValue,
                                                   BitesImageName.medium2part3.rawValue,
                                                   BitesImageName.medium2part4.rawValue,
                                                   BitesImageName.medium2part5.rawValue,
                                                   BitesImageName.medium2part6.rawValue,
                                                   BitesImageName.medium2part7.rawValue,
                                                   BitesImageName.medium2part8.rawValue,
                                                   BitesImageName.medium2part9.rawValue,
                                                   BitesImageName.medium2part10.rawValue,
                                                   BitesImageName.medium2part11.rawValue,
                                                   BitesImageName.medium2part12.rawValue,
                                                   BitesImageName.medium2part13.rawValue,
                                                   BitesImageName.medium2part14.rawValue,
                                                   BitesImageName.medium2part15.rawValue,
                                                   BitesImageName.medium2part16.rawValue,
                                                   BitesImageName.medium2part17.rawValue,
                                                   BitesImageName.medium2part18.rawValue,
                                                   BitesImageName.medium2part19.rawValue,
                                                   BitesImageName.medium2part20.rawValue,
                                                   BitesImageName.medium2part21.rawValue,
                                                   BitesImageName.medium2part22.rawValue,
                                                   BitesImageName.medium2part23.rawValue,
                                                   BitesImageName.medium2part24.rawValue,
                                                   BitesImageName.medium2part25.rawValue]),
                        
                        PuzzleModel(image: BitesImageName.medium3.rawValue,
                                    name: "Pancake Cake",
                                    ingredients: "15 pancakes, 300 ml whipped cream, 200 g sugar, berries for decoration.",
                                    cookingTime: "1 hour",
                                    recipe: "Spread whipped cream with sugar on each pancake, stack them into a layered cake. Decorate with berries and let it soak for 30 minutes.",
                                    xPosition: [5.4, 2.979, 1.99, 1.449, 1.19, 5.4, 2.82, 1.99, 1.489, 1.19, 5.4, 2.82, 1.92, 1.45, 1.19, 6, 3.15, 1.99, 1.45, 1.19, 6, 3.15, 2.065, 1.49, 1.19],
                                    yPosition: [1.45, 1.473, 1.473, 1.45, 1.473, 1.68, 1.68, 1.71, 1.68, 1.68, 2, 1.96, 2.045, 2.045, 2, 2.41, 2.41, 2.54, 2.47, 2.54, 3.13, 3.13, 3.24, 3.13, 3.24],
                                    puzzleImages: [BitesImageName.medium3part1.rawValue,
                                                   BitesImageName.medium3part2.rawValue,
                                                   BitesImageName.medium3part3.rawValue,
                                                   BitesImageName.medium3part4.rawValue,
                                                   BitesImageName.medium3part5.rawValue,
                                                   BitesImageName.medium3part6.rawValue,
                                                   BitesImageName.medium3part7.rawValue,
                                                   BitesImageName.medium3part8.rawValue,
                                                   BitesImageName.medium3part9.rawValue,
                                                   BitesImageName.medium3part10.rawValue,
                                                   BitesImageName.medium3part11.rawValue,
                                                   BitesImageName.medium3part12.rawValue,
                                                   BitesImageName.medium3part13.rawValue,
                                                   BitesImageName.medium3part14.rawValue,
                                                   BitesImageName.medium3part15.rawValue,
                                                   BitesImageName.medium3part16.rawValue,
                                                   BitesImageName.medium3part17.rawValue,
                                                   BitesImageName.medium3part18.rawValue,
                                                   BitesImageName.medium3part19.rawValue,
                                                   BitesImageName.medium3part20.rawValue,
                                                   BitesImageName.medium3part21.rawValue,
                                                   BitesImageName.medium3part22.rawValue,
                                                   BitesImageName.medium3part23.rawValue,
                                                   BitesImageName.medium3part24.rawValue,
                                                   BitesImageName.medium3part25.rawValue]),
                        
                        PuzzleModel(image: BitesImageName.medium4.rawValue,
                                    name: "Pancho Cake",
                                    ingredients: "1 chocolate sponge cake, 500 ml sour cream, 150 g sugar, 100 g nuts, 100 g cherries.",
                                    cookingTime: "1 hour 30 minutes",
                                    recipe: "Break the sponge cake into pieces, mix with sour cream, nuts, and cherries. Shape it into a dome, then decorate with chocolate glaze.",
                                    xPosition: [6, 3.16, 1.99, 1.49, 1.22, 5.4, 2.83, 1.92, 1.489, 1.22, 6, 3.16, 2.07, 1.54, 1.2217, 6, 2.98, 1.99, 1.53, 1.22, 5.4, 2.83, 1.92, 1.45, 1.193],
                                    yPosition: [1.45, 1.45, 1.45, 1.473, 1.473, 1.65, 1.68, 1.65, 1.71, 1.71, 2, 2, 1.96, 2.044, 2, 2.47, 2.47, 2.47, 2.54, 2.47, 3.13, 3.235, 3.235, 3.235, 3.235],
                                    puzzleImages: [BitesImageName.medium4part1.rawValue,
                                                   BitesImageName.medium4part2.rawValue,
                                                   BitesImageName.medium4part3.rawValue,
                                                   BitesImageName.medium4part4.rawValue,
                                                   BitesImageName.medium4part5.rawValue,
                                                   BitesImageName.medium4part6.rawValue,
                                                   BitesImageName.medium4part7.rawValue,
                                                   BitesImageName.medium4part8.rawValue,
                                                   BitesImageName.medium4part9.rawValue,
                                                   BitesImageName.medium4part10.rawValue,
                                                   BitesImageName.medium4part11.rawValue,
                                                   BitesImageName.medium4part12.rawValue,
                                                   BitesImageName.medium4part13.rawValue,
                                                   BitesImageName.medium4part14.rawValue,
                                                   BitesImageName.medium4part15.rawValue,
                                                   BitesImageName.medium4part16.rawValue,
                                                   BitesImageName.medium4part17.rawValue,
                                                   BitesImageName.medium4part18.rawValue,
                                                   BitesImageName.medium4part19.rawValue,
                                                   BitesImageName.medium4part20.rawValue,
                                                   BitesImageName.medium4part21.rawValue,
                                                   BitesImageName.medium4part22.rawValue,
                                                   BitesImageName.medium4part23.rawValue,
                                                   BitesImageName.medium4part24.rawValue,
                                                   BitesImageName.medium4part25.rawValue])]
    //MARK: - HARD
    let hardPuzzle = [PuzzleModel(image: BitesImageName.hard1.rawValue,
                                  name: "Pavlova",
                                  ingredients: "4 egg whites, 200 g sugar, 1 tsp cornstarch, 200 ml whipped cream, berries.",
                                  cookingTime: "1 hour 20 minutes",
                                  recipe: "Whip egg whites with sugar, add cornstarch, and shape into a meringue base. Bake at 120°C (250°F) for 90 minutes. Top with whipped cream and berries.",
                                  xPosition: [7, 3.55, 2.29, 1.74, 1.4, 1.2, 7, 3.75, 2.37, 1.79, 1.465, 1.224, 6.3, 3.54, 2.37, 1.79, 1.47, 1.224, 7, 3.75, 2.37, 1.74, 1.405, 1.2, 7, 3.75, 2.47, 1.835, 1.47, 1.225, 6.3, 3.54, 2.48, 1.84, 1.435, 1.202],
                                  yPosition: [1.43, 1.4485, 1.43, 1.43, 1.4485, 1.4485, 1.59, 1.613, 1.59, 1.613, 1.635, 1.635, 1.85, 1.85, 1.82, 1.85, 1.85, 1.85, 2.21, 2.21, 2.17, 2.17, 2.126, 2.126, 2.62, 2.62, 2.68, 2.62, 2.62, 2.62, 3.2, 3.2, 3.3, 3.2, 3.3, 3.3],
                                  puzzleImages: [BitesImageName.hard1part1.rawValue,
                                                 BitesImageName.hard1part2.rawValue,
                                                 BitesImageName.hard1part3.rawValue,
                                                 BitesImageName.hard1part4.rawValue,
                                                 BitesImageName.hard1part5.rawValue,
                                                 BitesImageName.hard1part6.rawValue,
                                                 BitesImageName.hard1part7.rawValue,
                                                 BitesImageName.hard1part8.rawValue,
                                                 BitesImageName.hard1part9.rawValue,
                                                 BitesImageName.hard1part10.rawValue,
                                                 BitesImageName.hard1part11.rawValue,
                                                 BitesImageName.hard1part12.rawValue,
                                                 BitesImageName.hard1part13.rawValue,
                                                 BitesImageName.hard1part14.rawValue,
                                                 BitesImageName.hard1part15.rawValue,
                                                 BitesImageName.hard1part16.rawValue,
                                                 BitesImageName.hard1part17.rawValue,
                                                 BitesImageName.hard1part18.rawValue,
                                                 BitesImageName.hard1part19.rawValue,
                                                 BitesImageName.hard1part20.rawValue,
                                                 BitesImageName.hard1part21.rawValue,
                                                 BitesImageName.hard1part22.rawValue,
                                                 BitesImageName.hard1part23.rawValue,
                                                 BitesImageName.hard1part24.rawValue,
                                                 BitesImageName.hard1part25.rawValue,
                                                 BitesImageName.hard1part26.rawValue,
                                                 BitesImageName.hard1part27.rawValue,
                                                 BitesImageName.hard1part28.rawValue,
                                                 BitesImageName.hard1part29.rawValue,
                                                 BitesImageName.hard1part30.rawValue,
                                                 BitesImageName.hard1part31.rawValue,
                                                 BitesImageName.hard1part32.rawValue,
                                                 BitesImageName.hard1part33.rawValue,
                                                 BitesImageName.hard1part34.rawValue,
                                                 BitesImageName.hard1part35.rawValue,
                                                 BitesImageName.hard1part36.rawValue]),
                      PuzzleModel(image: BitesImageName.hard2.rawValue,
                                  name: "Pudding",
                                  ingredients: "500 ml milk, 50 g sugar, 50 g cornstarch, vanilla.",
                                  cookingTime: "40 minutes",
                                  recipe: "Dissolve cornstarch and sugar in milk, cook over low heat until thickened. Cool and serve, garnished as desired.",
                                  xPosition: [6, 3.3, 2.26, 1.765, 1.45, 1.205, 6.62, 3.68, 2.34, 1.765, 1.45, 1.205, 6, 3.3, 2.26, 1.77, 1.45, 1.204, 6.62, 3.46, 2.345, 1.82, 1.418, 1.181, 6, 3.46, 2.35, 1.72, 1.387, 1.181, 6, 3.46, 2.35, 1.72, 1.385, 1.182],
                                  yPosition: [1.43, 1.43, 1.43, 1.43, 1.4485, 1.43, 1.614, 1.591, 1.614, 1.591, 1.614, 1.591, 1.883, 1.852, 1.852, 1.822, 1.822, 1.852, 2.21, 2.167, 2.125, 2.125, 2.125, 2.21, 2.62, 2.62, 2.56, 2.62, 2.62, 2.62, 3.21, 3.305, 3.21, 3.305, 3.305, 3.21],
                                  puzzleImages: [BitesImageName.hard2part1.rawValue,
                                                 BitesImageName.hard2part2.rawValue,
                                                 BitesImageName.hard2part3.rawValue,
                                                 BitesImageName.hard2part4.rawValue,
                                                 BitesImageName.hard2part5.rawValue,
                                                 BitesImageName.hard2part6.rawValue,
                                                 BitesImageName.hard2part7.rawValue,
                                                 BitesImageName.hard2part8.rawValue,
                                                 BitesImageName.hard2part9.rawValue,
                                                 BitesImageName.hard2part10.rawValue,
                                                 BitesImageName.hard2part11.rawValue,
                                                 BitesImageName.hard2part12.rawValue,
                                                 BitesImageName.hard2part13.rawValue,
                                                 BitesImageName.hard2part14.rawValue,
                                                 BitesImageName.hard2part15.rawValue,
                                                 BitesImageName.hard2part16.rawValue,
                                                 BitesImageName.hard2part17.rawValue,
                                                 BitesImageName.hard2part18.rawValue,
                                                 BitesImageName.hard2part19.rawValue,
                                                 BitesImageName.hard2part20.rawValue,
                                                 BitesImageName.hard2part21.rawValue,
                                                 BitesImageName.hard2part22.rawValue,
                                                 BitesImageName.hard2part23.rawValue,
                                                 BitesImageName.hard2part24.rawValue,
                                                 BitesImageName.hard2part25.rawValue,
                                                 BitesImageName.hard2part26.rawValue,
                                                 BitesImageName.hard2part27.rawValue,
                                                 BitesImageName.hard2part28.rawValue,
                                                 BitesImageName.hard2part29.rawValue,
                                                 BitesImageName.hard2part30.rawValue,
                                                 BitesImageName.hard2part31.rawValue,
                                                 BitesImageName.hard2part32.rawValue,
                                                 BitesImageName.hard2part33.rawValue,
                                                 BitesImageName.hard2part34.rawValue,
                                                 BitesImageName.hard2part35.rawValue,
                                                 BitesImageName.hard2part36.rawValue]),
                      PuzzleModel(image: BitesImageName.hard3.rawValue,
                                  name: "Tiramisu",
                                  ingredients: "200 g ladyfingers, 250 g mascarpone, 2 eggs, 100 g sugar, 200 ml coffee, cocoa powder.",
                                  cookingTime: "30 minutes + 4 hours for chilling",
                                  recipe: "Recipe: Beat egg yolks with sugar and mascarpone, then fold in whipped egg whites. Dip ladyfingers in coffee, layer with cream, dust with cocoa, and chill.",
                                  xPosition: [6.62, 3.43, 2.312, 1.793, 1.432, 1.192, 6.62, 3.43, 2.23, 1.745, 1.4, 1.17, 6.62, 3.63, 2.4, 1.79, 1.4, 1.17, 6, 3.45, 2.4, 1.742, 1.4, 1.192, 6, 3.27, 2.315, 1.793, 1.4, 1.17, 6.62, 3.645, 2.32, 1.7, 1.4, 1.192],
                                  yPosition: [1.4485, 1.43, 1.43, 1.43, 1.43, 1.4485, 1.638, 1.614, 1.614, 1.614, 1.591, 1.614, 1.885, 1.8528, 1.882, 1.88, 1.82, 1.85, 2.215, 2.174, 2.172, 2.214, 2.172, 2.214, 2.62, 2.62, 2.62, 2.62, 2.62, 2.685, 3.21, 3.21, 3.31, 3.22, 3.22, 3.31],
                                  puzzleImages: [BitesImageName.hard3part1.rawValue,
                                                 BitesImageName.hard3part2.rawValue,
                                                 BitesImageName.hard3part3.rawValue,
                                                 BitesImageName.hard3part4.rawValue,
                                                 BitesImageName.hard3part5.rawValue,
                                                 BitesImageName.hard3part6.rawValue,
                                                 BitesImageName.hard3part7.rawValue,
                                                 BitesImageName.hard3part8.rawValue,
                                                 BitesImageName.hard3part9.rawValue,
                                                 BitesImageName.hard3part10.rawValue,
                                                 BitesImageName.hard3part11.rawValue,
                                                 BitesImageName.hard3part12.rawValue,
                                                 BitesImageName.hard3part13.rawValue,
                                                 BitesImageName.hard3part14.rawValue,
                                                 BitesImageName.hard3part15.rawValue,
                                                 BitesImageName.hard3part16.rawValue,
                                                 BitesImageName.hard3part17.rawValue,
                                                 BitesImageName.hard3part18.rawValue,
                                                 BitesImageName.hard3part19.rawValue,
                                                 BitesImageName.hard3part20.rawValue,
                                                 BitesImageName.hard3part21.rawValue,
                                                 BitesImageName.hard3part22.rawValue,
                                                 BitesImageName.hard3part23.rawValue,
                                                 BitesImageName.hard3part24.rawValue,
                                                 BitesImageName.hard3part25.rawValue,
                                                 BitesImageName.hard3part26.rawValue,
                                                 BitesImageName.hard3part27.rawValue,
                                                 BitesImageName.hard3part28.rawValue,
                                                 BitesImageName.hard3part29.rawValue,
                                                 BitesImageName.hard3part30.rawValue,
                                                 BitesImageName.hard3part31.rawValue,
                                                 BitesImageName.hard3part32.rawValue,
                                                 BitesImageName.hard3part33.rawValue,
                                                 BitesImageName.hard3part34.rawValue,
                                                 BitesImageName.hard3part35.rawValue,
                                                 BitesImageName.hard3part36.rawValue]),
                      PuzzleModel(image: BitesImageName.hard4.rawValue,
                                  name: "",
                                  ingredients: "",
                                  cookingTime: "",
                                  recipe: "",
                                  xPosition: [5.8, 2.61, 1.62, 1.241, 5.12, 2.46, 1.684, 1.278, 5.8, 2.775, 1.753, 1.279, 5.8, 2.6, 1.62, 1.242],
                                  yPosition: [1.5, 1.5, 1.5, 1.471, 1.83, 1.83, 1.787, 1.746, 2.275, 2.275, 2.275, 2.21, 3, 3, 3.13, 3.01],
                                  puzzleImages: [""])]
}
