import SwiftUI

struct BitesLoadingModel {
    let arrayOfLoadingText = ["LOADING.", "LOADING..", "LOADING..."]
    
    let easyPuzzle = [PuzzleModel(image: BitesImageName.easy1.rawValue,
                                  name: "Chocolate Fondue",
                                  ingredients: "200 g dark chocolate, 150 ml cream (20-30%), fruits and berries of your choice.",
                                  cookingTime: "10 minutes",
                                  recipe: "Melt the chocolate with cream in a water bath until smooth. Prepare sliced fruits or berries. Serve warm, dipping pieces into the chocolate.",
                                  xPosition: [5.8, 2.61, 1.62, 1.241, 5.12, 2.46, 1.684, 1.278, 5.8, 2.775, 1.753, 1.279, 5.8, 2.6, 1.62, 1.242],
                                  yPosition: [1.5, 1.5, 1.5, 1.471, 1.83, 1.83, 1.787, 1.746, 2.275, 2.275, 2.275, 2.21, 3, 3, 3.13, 3.01],
                                  puzzleImages: [BitesImageName.easyPart1.rawValue,
                                                 BitesImageName.easyPart2.rawValue,
                                                 BitesImageName.easyPart3.rawValue,
                                                 BitesImageName.easyPart4.rawValue,
                                                 BitesImageName.easyPart5.rawValue,
                                                 BitesImageName.easyPart6.rawValue,
                                                 BitesImageName.easyPart7.rawValue,
                                                 BitesImageName.easyPart8.rawValue,
                                                 BitesImageName.easyPart9.rawValue,
                                                 BitesImageName.easyPart10.rawValue,
                                                 BitesImageName.easyPart11.rawValue,
                                                 BitesImageName.easyPart12.rawValue,
                                                 BitesImageName.easyPart13.rawValue,
                                                 BitesImageName.easyPart14.rawValue,
                                                 BitesImageName.easyPart15.rawValue,
                                                 BitesImageName.easyPart16.rawValue]),
                      PuzzleModel(image: BitesImageName.easy2.rawValue,
                                  name: "Cotton Cake (Japanese Cheesecake)",
                                  ingredients: "200 g cream cheese, 50 g butter, 120 ml milk, 60 g flour, 20 g cornstarch, 6 eggs, 140 g sugar.",
                                  cookingTime: "1 hour 30 minutes",
                                  recipe: "Mix melted cheese, butter, and milk; add flour and yolks, then gently fold in whipped egg whites with sugar. Bake in a water bath at 160°C (320°F) for 60 minutes, cool, and serve.",
                                  xPosition: [4.9, 2.55, 1.72, 1.26, 5.55, 2.551, 1.593, 1.2239, 4.92, 2.41, 1.653, 1.26, 4.9, 2.545, 1.72, 1.26],
                                  yPosition: [1.495, 1.466, 1.466, 1.466, 1.78, 1.78, 1.74, 1.78, 2.2, 2.265, 2.2, 2.335, 2.99, 2.99, 2.99, 3.11],
                                  puzzleImages: [BitesImageName.easy2part1.rawValue,
                                                 BitesImageName.easy2part2.rawValue,
                                                 BitesImageName.easy2part3.rawValue,
                                                 BitesImageName.easy2part4.rawValue,
                                                 BitesImageName.easy2part5.rawValue,
                                                 BitesImageName.easy2part6.rawValue,
                                                 BitesImageName.easy2part7.rawValue,
                                                 BitesImageName.easy2part8.rawValue,
                                                 BitesImageName.easy2part9.rawValue,
                                                 BitesImageName.easy2part10.rawValue,
                                                 BitesImageName.easy2part11.rawValue,
                                                 BitesImageName.easy2part12.rawValue,
                                                 BitesImageName.easy2part13.rawValue,
                                                 BitesImageName.easy2part14.rawValue,
                                                 BitesImageName.easy2part15.rawValue,
                                                 BitesImageName.easy2part16.rawValue]),
                      PuzzleModel(image: BitesImageName.easy3.rawValue,
                                  name: "Croquembouche",
                                  ingredients: "20 profiteroles, 200 g sugar, 50 ml water, whipped cream or custard.",
                                  cookingTime: "2 hours",
                                  recipe: "Fill profiteroles with cream. Boil sugar with water to make caramel, dip profiteroles, and stack them into a pyramid. Let the caramel harden before serving.",
                                  xPosition: [5.6, 2.57, 1.66, 1.27, 4.95, 2.42, 1.599, 1.235, 5.6, 2.56, 1.662, 1.27, 4.95, 2.56, 1.73, 1.273],
                                  yPosition: [1.495, 1.495, 1.495, 1.466, 1.82, 1.82, 1.82, 1.778, 2.331, 2.331, 2.26, 2.33, 3.11, 3.11, 2.985, 3.104],
                                  puzzleImages: [BitesImageName.easy3part1.rawValue,
                                                 BitesImageName.easy3part2.rawValue,
                                                 BitesImageName.easy3part3.rawValue,
                                                 BitesImageName.easy3part4.rawValue,
                                                 BitesImageName.easy3part5.rawValue,
                                                 BitesImageName.easy3part6.rawValue,
                                                 BitesImageName.easy3part7.rawValue,
                                                 BitesImageName.easy3part8.rawValue,
                                                 BitesImageName.easy3part9.rawValue,
                                                 BitesImageName.easy3part10.rawValue,
                                                 BitesImageName.easy3part11.rawValue,
                                                 BitesImageName.easy3part12.rawValue,
                                                 BitesImageName.easy3part13.rawValue,
                                                 BitesImageName.easy3part14.rawValue,
                                                 BitesImageName.easy3part15.rawValue,
                                                 BitesImageName.easy3part16.rawValue]),
                      PuzzleModel(image: BitesImageName.easy4.rawValue,
                                  name: "Eclairs",
                                  ingredients: "125 ml water, 50 g butter, 75 g flour, 2 eggs, 200 g custard, 100 g chocolate.",
                                  cookingTime: "1 hour 15 minutes",
                                  recipe: "Prepare choux pastry, bake eclairs for 25 minutes at 200°C (390°F). Let them cool, fill with custard, and glaze with melted chocolate.",
                                  xPosition: [4.95, 2.418, 1.6, 1.23, 4.95, 2.42, 1.66, 1.266, 4.95, 2.42, 1.663, 1.266, 4.95, 2.56, 1.66, 1.23],
                                  yPosition: [1.495, 1.466, 1.465, 1.465, 1.78, 1.74, 1.74, 1.739, 2.2, 2.2, 2.265, 2.2, 2.99, 2.99, 3.11, 2.99],
                                  puzzleImages: [BitesImageName.easy4part1.rawValue,
                                                 BitesImageName.easy4part2.rawValue,
                                                 BitesImageName.easy4part3.rawValue,
                                                 BitesImageName.easy4part4.rawValue,
                                                 BitesImageName.easy4part5.rawValue,
                                                 BitesImageName.easy4part6.rawValue,
                                                 BitesImageName.easy4part7.rawValue,
                                                 BitesImageName.easy4part8.rawValue,
                                                 BitesImageName.easy4part9.rawValue,
                                                 BitesImageName.easy4part10.rawValue,
                                                 BitesImageName.easy4part11.rawValue,
                                                 BitesImageName.easy4part12.rawValue,
                                                 BitesImageName.easy4part13.rawValue,
                                                 BitesImageName.easy4part14.rawValue,
                                                 BitesImageName.easy4part15.rawValue,
                                                 BitesImageName.easy4part16.rawValue])]
}


